#! /bin/sh

# input checking
isRecursive=0
case $# in
    0) D='.';;
    1) if [ $1 = '-r' ]
       then
           D='.'
           isRecursive=1
       else
           D=$1
           isRecursive=0
       fi;;
    2) if [ $1 = '-r' ]
       then
           isRecursive=1
       else
           echo 'Your first operand is wrong' >&2
           exit 1
       fi
       D=$2;;
    *) echo 'You have given more than two operands' >&2
       exit 1;;
    esac
if [ ${D:0:1} == "-" ]
then
    echo "Your operand starts with -" >&2
    exit 1
elif [ ! -d $D ]
then
    echo "Your operand is not a directory" >&2
    exit 1
elif [ ! -r $D ]
then
    echo "Your directory is not readable" >&2
    exit 1
fi

# checking for poornames
reg="$reg([^\/]{15,}\..*$)|"
reg="$reg\/*[^a-zA-Z\._\/-][^\/]*$|"
reg="$reg\/-[^\/]*$|"
reg="$reg\/\.[^.]+[^\/]*$|"
reg="$reg\/\.\.[^\/]+$"

if [ $isRecursive = 1 ]
    then
    { find -H $D | 
    grep -E $reg & find -H $D | 
    sort -f | uniq -Di; } | sort -f | uniq -u
    { find -H $D | 
    grep -E $reg & find -H $D | 
    sort -f | uniq -Di; } | sort -f | uniq -d
else
    { find -H $D -maxdepth 1 | 
    grep -E $reg & find -H $D -maxdepth 1 | 
    sort -f | uniq -Di; } | sort -f | uniq -u 
    { find -H $D -maxdepth 1 | 
    grep -E $reg & find -H $D -maxdepth 1 | 
    sort -f | uniq -Di; } | sort -f | uniq -d
fi



